-- add_rules("mode.debug", "mode.release")
add_repositories("xege-repo git@gitee.com:xege/ege-xrepo.git")
add_requires("xege 20.08")
add_requires("imgui", {configs = {glfw_opengl3 = true}})

add_defines("__STDC_LIMIT_MACROS")
includes("./codebase/lib")
includes("./codebase/app")
includes("./codebase/ui")
includes("./codebase/elib")
target ("main")
	-- add_rules("mode.release")
	add_packages("xege")
	set_kind ("binary")
	set_languages("c++2a")
	-- add_files ("$(projectdir)/src/core.cc")
	add_deps("app", "animation")
	add_deps("libxbmp", "ui", "elib", "base64")
	add_files ("$(projectdir)/src/main.cc")
	set_warnings("everything")
	set_rundir("$(projectdir)")
